#!/usr/bin/env python3
"""
Stage 6 — Seed Backend

Reads verified content (Stage 4) and solved PYQs (Stage 5) and generates
a TypeScript data file for the Cloudflare Worker backend.

Usage:
    cd pipeline
    python -m 06_seed.seed_backend --subject maths-12 [--all]

Output: backend/src/data/generated.ts

This replaces the old backend/src/generatedData.ts with properly structured,
verified data that matches the backend TypeScript interfaces.
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import VERIFIED_DIR, SOLVED_DIR, BACKEND_DIR, SUBJECTS, ensure_dirs
from schemas import VerifiedSubject, SolvedPYQSet, SeedData


def load_verified(subject_id: str) -> VerifiedSubject | None:
    """Load verified content for a subject."""
    path = VERIFIED_DIR / f"{subject_id}.json"
    if path.exists():
        return VerifiedSubject.model_validate_json(path.read_text())
    print(f"  ⚠️  No verified data for {subject_id}")
    return None


def load_solved_pyqs(subject_id: str) -> SolvedPYQSet | None:
    """Load solved PYQs for a subject."""
    path = SOLVED_DIR / f"{subject_id}_pyqs.json"
    if path.exists():
        return SolvedPYQSet.model_validate_json(path.read_text())
    print(f"  ⚠️  No solved PYQs for {subject_id}")
    return None


def escape_ts(s: str) -> str:
    """Escape a string for use in TypeScript source code."""
    return (
        s.replace("\\", "\\\\")
         .replace("'", "\\'")
         .replace("\n", "\\n")
         .replace("\r", "")
         .replace("\t", "\\t")
    )


def generate_ts(seed: SeedData) -> str:
    """Generate TypeScript source from SeedData."""
    lines = [
        f"// AUTO-GENERATED by pipeline/06_seed/seed_backend.py — do not edit by hand",
        f"// Generated at: {seed.generated_at}",
        "",
        "import type { Subject, Chapter, Topic, TopicContent, Pyq, PyqExplanation } from '../types'",
        "",
    ]

    # Subjects
    lines.append("export const subjects: Subject[] = [")
    for s in seed.subjects:
        lines.append(f"  {{ id: '{s.id}', name: '{escape_ts(s.name)}', classLevel: '{s.class_level}', description: '{escape_ts(s.description)}', icon: '{s.icon}', totalMarks: {s.total_marks} }},")
    lines.append("]")
    lines.append("")

    # Chapters
    lines.append("export const chapters: Chapter[] = [")
    for c in seed.chapters:
        lines.append(f"  {{ id: '{c.id}', subjectId: '{c.subject_id}', title: '{escape_ts(c.title)}', orderIndex: {c.order_index} }},")
    lines.append("]")
    lines.append("")

    # Topics
    lines.append("export const topics: Topic[] = [")
    for t in seed.topics:
        lines.append(f"  {{ id: '{t.id}', chapterId: '{t.chapter_id}', title: '{escape_ts(t.title)}', orderIndex: {t.order_index}, highYieldScore: {t.high_yield_score}, estMinutes: {t.est_minutes} }},")
    lines.append("]")
    lines.append("")

    # TopicContents
    lines.append("export const topicContents: TopicContent[] = [")
    for tc in seed.topic_contents:
        bullets = json.dumps([escape_ts(b) for b in tc.summary_bullets])
        mistakes = json.dumps([escape_ts(m) for m in tc.common_mistakes])
        lines.append(f"  {{ id: '{tc.id}', topicId: '{tc.topic_id}', lang: '{tc.lang}', summaryBullets: {bullets}, whyImportant: '{escape_ts(tc.why_important)}', commonMistakes: {mistakes} }},")
    lines.append("]")
    lines.append("")

    # PYQs
    lines.append("export const pyqs: Pyq[] = [")
    for p in seed.pyqs:
        lines.append(f"  {{ id: '{p.id}', subjectId: '{p.subject_id}', topicId: '{p.topic_id}', year: '{p.year}', session: '{p.session}', questionText: '{escape_ts(p.question_text)}', marks: {p.marks}, difficulty: '{p.difficulty}', frequencyScore: {p.frequency_score}, questionType: '{p.question_type}' }},")
    lines.append("]")
    lines.append("")

    # PYQ Explanations
    lines.append("export const pyqExplanations: PyqExplanation[] = [")
    for e in seed.pyq_explanations:
        steps = json.dumps([escape_ts(s) for s in e.steps])
        hints = json.dumps([escape_ts(h) for h in e.hints])
        lines.append(f"  {{ id: '{e.id}', pyqId: '{e.pyq_id}', lang: '{e.lang}', steps: {steps}, hints: {hints}, answer: '{escape_ts(e.answer)}', commonErrors: '{escape_ts(e.common_errors)}' }},")
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Stage 6: Generate backend data from verified pipeline output")
    parser.add_argument("--subject", help="Subject ID to seed (e.g. maths-12)")
    parser.add_argument("--all", action="store_true", help="Seed all known subjects")
    args = parser.parse_args()

    ensure_dirs()

    subjects_to_seed = []
    if args.all:
        subjects_to_seed = list(SUBJECTS.keys())
    elif args.subject:
        subjects_to_seed = [args.subject]
    else:
        print("❌ Specify --subject <id> or --all")
        sys.exit(1)

    all_subjects = []
    all_chapters = []
    all_topics = []
    all_topic_contents = []
    all_pyqs = []
    all_pyq_explanations = []

    for sid in subjects_to_seed:
        print(f"\n📦 Loading: {sid}")

        verified = load_verified(sid)
        if verified:
            all_subjects.append(verified.subject)
            for ch in verified.chapters:
                all_chapters.append(ch.chapter)
                all_topics.extend(ch.topics)
                all_topic_contents.extend(ch.topic_contents)
            print(f"  ✅ {len(verified.chapters)} chapters, "
                  f"{sum(len(c.topics) for c in verified.chapters)} topics, "
                  f"{sum(len(c.topic_contents) for c in verified.chapters)} contents")

        solved = load_solved_pyqs(sid)
        if solved:
            all_pyqs.extend(solved.pyqs)
            all_pyq_explanations.extend(solved.explanations)
            print(f"  ✅ {len(solved.pyqs)} PYQs, {len(solved.explanations)} explanations")

    if not all_subjects:
        print("\n❌ No data to seed. Run stages 3-5 first.")
        sys.exit(1)

    seed = SeedData(
        generated_at=datetime.now(timezone.utc).isoformat(),
        subjects=all_subjects,
        chapters=all_chapters,
        topics=all_topics,
        topic_contents=all_topic_contents,
        pyqs=all_pyqs,
        pyq_explanations=all_pyq_explanations,
    )

    # Generate TypeScript
    ts_code = generate_ts(seed)
    output_file = BACKEND_DIR / "src" / "data" / "generated.ts"
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(ts_code, encoding="utf-8")

    # Also write seed JSON for reference
    json_file = BACKEND_DIR / "src" / "data" / "generated.json"
    json_file.write_text(seed.model_dump_json(indent=2), encoding="utf-8")

    print(f"\n🎉 Backend data generated!")
    print(f"   TypeScript: {output_file}")
    print(f"   JSON:       {json_file}")
    print(f"   Subjects:   {len(all_subjects)}")
    print(f"   Chapters:   {len(all_chapters)}")
    print(f"   Topics:     {len(all_topics)}")
    print(f"   Contents:   {len(all_topic_contents)}")
    print(f"   PYQs:       {len(all_pyqs)}")


if __name__ == "__main__":
    main()
