#!/usr/bin/env ts-node
import fs from 'fs'
import path from 'path'

function estimateMinutesFromRawText(rawText: string): number {
  const words = rawText.trim().split(/\s+/).filter(Boolean).length
  const minutes = Math.ceil(words / 140)
  return Math.max(5, Math.min(45, minutes))
}

function safeTsString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, '\\n')
}

const contentDir = path.resolve(__dirname, '../content')
if (!fs.existsSync(contentDir)) {
  console.error('content/ directory not found')
  process.exit(1)
}

const classDirs = fs.readdirSync(contentDir).filter((d) => d.startsWith('class'))
if (classDirs.length === 0) {
  console.error('No class* directories under content/')
  process.exit(1)
}

const outPath = path.resolve(__dirname, '../backend/src/mockData.ts')

let header = `// AUTO-GENERATED by scripts/regenerateMock.ts — do not edit by hand\n// Generated at: ${new Date().toISOString()}\n\n`

let body = header
body += `export interface Subject { id: string; name: string; classLevel: '10' | '12'; description: string; icon: string }\n\n`
body += `export interface Chapter { id: string; subjectId: string; title: string; orderIndex: number }\n\n`
body += `export interface Topic { id: string; chapterId: string; title: string; orderIndex: number; estMinutes: number; highYieldScore: number }\n\n`
body += `export interface TopicContent { id: string; topicId: string; lang: 'en' | 'hi' | 'hinglish'; summaryBullets: string[]; whyImportant: string; commonMistakes: string[] }\n\n`
body += `export interface Pyq { id: string; subjectId: string; topicId: string; year: string; session: 'March' | 'October'; questionText: string; marks: number; difficulty: 'easy' | 'medium' | 'hard'; frequencyScore: number; questionType: 'mcq' | 'short' | 'long' | 'numerical' }\n\n`
body += `export interface PyqExplanation { id: string; pyqId: string; lang: 'en' | 'hi' | 'hinglish'; hints: string[]; steps: string[]; answer: string }\n\n`

let subjectsArr: string[] = []
let chaptersArr: string[] = []
let topicsArr: string[] = []
let topicContentsArr: string[] = []

for (const cls of classDirs) {
  const dir = path.join(contentDir, cls)
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.raw.json'))
  for (const rawFile of files) {
    const base = rawFile.replace('.raw.json', '')
    const rawPath = path.join(dir, rawFile)
    const contentPath = path.join(dir, `${base}.content.json`)
    if (!fs.existsSync(rawPath)) continue
    const raw = JSON.parse(fs.readFileSync(rawPath, 'utf-8'))
    const content = fs.existsSync(contentPath) ? JSON.parse(fs.readFileSync(contentPath, 'utf-8')) : null

    // subject
    const subj = raw.subject
    subjectsArr.push(`  { id: '${safeTsString(subj.id)}', name: '${safeTsString(subj.name)}', classLevel: '${safeTsString(subj.classLevel)}', description: '${safeTsString(subj.description ?? '')}', icon: '${safeTsString(subj.icon ?? '📘')}' },`)

    // chapters and topics from raw
    for (const ch of raw.chapters) {
      chaptersArr.push(`  { id: '${safeTsString(ch.id)}', subjectId: '${safeTsString(subj.id)}', title: '${safeTsString(ch.title)}', orderIndex: ${ch.orderIndex} },`)
      for (const t of ch.topics) {
        const est = estimateMinutesFromRawText(t.rawText ?? '')
        topicsArr.push(`  { id: '${safeTsString(t.id)}', chapterId: '${safeTsString(ch.id)}', title: '${safeTsString(t.title)}', orderIndex: ${t.orderIndex}, estMinutes: ${est}, highYieldScore: 75 },`)
      }
    }

    // topic contents from content file
    if (content && Array.isArray(content.topics)) {
      for (const c of content.topics) {
        const bullets = (c.summaryBullets || []).map((b: string) => `      '${safeTsString(b)}'`).join(',\n')
        const mistakes = (c.commonMistakes || []).map((m: string) => `      '${safeTsString(m)}'`).join(',\n')
        topicContentsArr.push(`  {\n    id: '${safeTsString(c.id)}',\n    topicId: '${safeTsString(c.topicId)}',\n    lang: '${safeTsString(c.lang || 'en')}',\n    summaryBullets: [\n${bullets}\n    ],\n    whyImportant: '${safeTsString(c.whyImportant || '')}',\n    commonMistakes: [\n${mistakes}\n    ],\n  },`)
      }
    }
  }
}

body += `export const subjects = [\n${subjectsArr.join('\n')}\n]\n\n`
body += `export const chapters = [\n${chaptersArr.join('\n')}\n]\n\n`
body += `export const topics = [\n${topicsArr.join('\n')}\n]\n\n`
body += `export const topicContents = [\n${topicContentsArr.join('\n')}\n]\n\n`
body += `export const pyqs = []\n\nexport const pyqExplanations = []\n`

fs.writeFileSync(outPath, body, 'utf-8')
console.log('Wrote', outPath)
